AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  pricemonitor:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: pricemonitor/lambda_function.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::287560958655:role/adminlambda-april22'
      CodeUri: .debug/
